### ISSUE TITLE
Direct Channel Changing

### ISSUE THREAD

**Issue by mattstralia** [jordenc/com.sony.bravia.androidtv#6]
Hello,

I'm not sure if this is the right place to ask, but is there a way to use Homey / Google Assistant to directly change the channel without creating a flow/virtual device for each channel possible?
i.e. "Homey, turn the Bravia to channel 78".

**Comment by jordenc** [comment]
I don't know if this can be easily done. I would think that you could use the "Something was said containing..." flow card, where you will in "turn the Bravia" or something... then you can perhaps use the "text" tag to fill in the channel number.
Except you would need to cut off everything except the number from the tag... so I'm not sure how to do that.

I would try to ask via the https://community.athom.com/ forum.
